apiVersion: v1
kind: Service
metadata:
  name: enterprise-system-004618-1eqy-service
spec:
  selector:
    app: enterprise-system-004618-1eqy
  ports:
  - port: 80
    targetPort: 8000
  type: ClusterIP
